parameters:
    uploads_rooms_directory: "%kernel.project_dir%/public/uploads/rooms"
    uploads_pictures_directory: "%kernel.project_dir%/public/uploads/pictures"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: "../src/"

    App\Controller\RoomController:
        arguments:
            $uploadsRoomsDirectory: "%uploads_rooms_directory%"

    App\Controller\PictureController:
        arguments:
            $uploadsPicturesDirectory: "%uploads_pictures_directory%"
